config/routes.rb
HelpTheNeedy::Application.routes.draw do
  resources :needy_people

  get "static_pages/index"
  get "static_pages/needy_people"
  get "elders_quorum/index"
  get "relief_society/index"
  get "bishopric/index"

end

app/models/needy_person.rb
class NeedyPerson < ActiveRecord::Base

	def name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bishopric_controller.rb
class BishopricController < ApplicationController
  def index
  	@bish_needy_people = NeedyPerson.where("organization = 'bishopric'")
  end
end

app/controllers/elders_quorum_controller.rb
class EldersQuorumController < ApplicationController
  def index
  	@eq_needy_people = NeedyPerson.where("organization = 'elders quorum'")
  end
end

app/controllers/needy_people_controller.rb
class NeedyPeopleController < ApplicationController
  before_action :set_needy_person, only: [:show, :edit, :update, :destroy]

  # GET /needy_people
  # GET /needy_people.json
  def index
    @needy_people = NeedyPerson.all
  end

  # GET /needy_people/1
  # GET /needy_people/1.json
  def show
  end

  # GET /needy_people/new
  def new
    @needy_person = NeedyPerson.new
  end

  # GET /needy_people/1/edit
  def edit
  end

  # POST /needy_people
  # POST /needy_people.json
  def create
    @needy_person = NeedyPerson.new(needy_person_params)

    respond_to do |format|
      if @needy_person.save
        format.html { redirect_to @needy_person, notice: 'Needy person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @needy_person }
      else
        format.html { render action: 'new' }
        format.json { render json: @needy_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needy_people/1
  # PATCH/PUT /needy_people/1.json
  def update
    respond_to do |format|
      if @needy_person.update(needy_person_params)
        format.html { redirect_to @needy_person, notice: 'Needy person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @needy_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needy_people/1
  # DELETE /needy_people/1.json
  def destroy
    @needy_person.destroy
    respond_to do |format|
      format.html { redirect_to needy_people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_needy_person
      @needy_person = NeedyPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def needy_person_params
      params.require(:needy_person).permit(:first_name, :last_name, :age, :address, :comments, :organization)
    end
end

app/controllers/relief_society_controller.rb
class ReliefSocietyController < ApplicationController
  def index
  	@rs_needy_people = NeedyPerson.where("organization = 'relief society'")
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def needy_people
  	@needy_people = NeedyPerson.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bishopric_helper.rb
module BishopricHelper
end

app/helpers/elders_quorum_helper.rb
module EldersQuorumHelper
end

app/helpers/needy_people_helper.rb
module NeedyPeopleHelper
end

app/helpers/relief_society_helper.rb
module ReliefSocietyHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bishopric/index.html.erb
<% provide(:title, 'Boston 1st Ward | Bishopric') %>

<% provide(:class, 'active') %>

<h2>People for Bishopric to focus on</h2>
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Organization</th>
				</tr>
			</thead>
			<tbody>
				<% for np in @bish_needy_people %>
				<tr>
					<th><%= np.name %></th>
					<th><%= np.age %></th>
					<th><%= np.address %></th>
					<th><%= np.comments %></th>
					<th><%= np.organization %></th>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/elders_quorum/index.html.erb
<% provide(:title, "Boston 1st Ward | Elders Quorum" %>

<h2>People for Elders Quorum to focus on</h2>
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Organization</th>
				</tr>
			</thead>
			<tbody>
				<% for np in @eq_needy_people %>
				<tr>
					<th><%= np.name %></th>
					<th><%= np.age %></th>
					<th><%= np.address %></th>
					<th><%= np.comments %></th>
					<th><%= np.organization %></th>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
	<ul class="title-area">
		<li class="name">
			<h1><%= link_to "Boston 1st Ward", static_pages_index_path %></h1>
		</li>
		<li class="toggle-topbar menu-icon"><%= link_to "Menu" %></li>
	</ul>

	<section class="top-bar-section">

		<ul class="left">
			<li><%= link_to "Bishopric", bishopric_index_path, :class => yield(:class) %></li>	
			<li><%= link_to "Relief Society", relief_society_index_path %></li>
			<li><%= link_to "Elders Quorum", elders_quorum_index_path %></li>
			<li><%= link_to "All People in Need", static_pages_needy_people_path %></li>
		</ul>
	</section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/nav' %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/needy_people/_form.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= form_for(@needy_person) do |f| %>
    <% if @needy_person.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@needy_person.errors.count, "error") %> prohibited this needy_person from being saved:</h2>

        <ul>
        <% @needy_person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :organization %><br>
      <%= f.text_field :organization %>
    </div>
    <div class="field">
      <%= f.label :comments %><br>
      <%= f.text_area :comments %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

app/views/needy_people/edit.html.erb
<h1>Editing needy_person</h1>

<%= render 'form' %>

<%= link_to 'Show', @needy_person %> |
<%= link_to 'Back', needy_people_path %>

app/views/needy_people/index.html.erb
<h1>Listing needy_people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Comments</th>
      <th>Organization</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @needy_people.each do |needy_person| %>
      <tr>
        <td><%= needy_person.name %></td>
        <td><%= needy_person.age %></td>
        <td><%= needy_person.address %></td>
        <td><%= needy_person.comments %></td>
        <td><%= needy_person.organization %></td>
        <td><%= link_to 'Show', needy_person %></td>
        <td><%= link_to 'Edit', edit_needy_person_path(needy_person) %></td>
        <td><%= link_to 'Destroy', needy_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Needy person', new_needy_person_path, :class => "button" %>

app/views/needy_people/new.html.erb
<h1>New Person of Need</h1>

		<%= render 'form' %>

		<%= link_to 'Back', needy_people_path %>

app/views/needy_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @needy_person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @needy_person.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @needy_person.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @needy_person.address %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @needy_person.comments %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @needy_person.organization %>
</p>

<%= link_to 'Edit', edit_needy_person_path(@needy_person) %> |
<%= link_to 'Back', needy_people_path %>

app/views/relief_society/index.html.erb
<% provide(:title, "Boston 1st Ward | RS" %>

<h2>People for Relief Society to focus on</h2>
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Organization</th>
				</tr>
			</thead>
			<tbody>
				<% for np in @rs_needy_people %>
				<tr>
					<th><%= np.name %></th>
					<th><%= np.age %></th>
					<th><%= np.address %></th>
					<th><%= np.comments %></th>
					<th><%= np.organization %></th>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/static_pages/index.html.erb
<% provide(:title, "Boston 1st Ward") %>

<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/static_pages/needy_people.html.erb
<h2>People in Need</h2>
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Organization</th>
				</tr>
			</thead>
			<tbody>
				<% for np in @needy_people %>
				<tr>
					<th><%= np.name %></th>
					<th><%= np.age %></th>
					<th><%= np.address %></th>
					<th><%= np.comments %></th>
					<th><%= np.organization %></th>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>